remote_theme: "BDHU/minimalist"
plugins:
- jekyll-remote-theme 
- jekyll-seo-tag
favicon: true
title: User5522
description: Yo does this work???
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
